--- gdb-8.0.1/gdb/configure.orig	2018-02-04 15:54:00.599198000 +0100
+++ gdb-8.0.1/gdb/configure	2018-02-04 15:53:04.392983200 +0100
@@ -9872,7 +9872,7 @@
         as_fn_error "failure running python-config --ldflags" "$LINENO" 5
       fi
     fi
-    python_prefix=`${python_prog} ${srcdir}/python/python-config.py --exec-prefix`
+    python_prefix=`cygpath -u "$(${python_prog} ${srcdir}/python/python-config.py --exec-prefix)"`
     if test $? != 0; then
       have_python_config=failed
       if test "${with_python}" != auto; then
